<a href="https://colab.research.google.com/github/SebastianJadczak/data-science/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Wstęp


In [2]:
import numpy as np
np.__version__

'1.19.5'

!D Array


In [10]:
x = np.array([1,3,5,6])
print(x)
print(x.size)
print(x.dtype)

y = np.array(["Ala ma kota", "Kota ma Alę", "A sierotka ma Rysia"])
print(y.size)
print(y.dtype)

[1 3 5 6]
4
int64
3
<U19


2D Array

In [19]:
q = np.array([[1,2,3],[1,2,3],[0,0,0]])
print(q)
print(q[2][2])
print(q.ndim)
print(q.shape)

[[1 2 3]
 [1 2 3]
 [0 0 0]]
0
2
(3, 3)
