<a href="https://colab.research.google.com/github/SebastianJadczak/data-science/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Wstęp


In [2]:
import numpy as np
np.__version__

'1.19.5'

!D Array


In [ ]:
x = np.array([1,3,5,6])
print(x)
print(x.size)
print(x.dtype)

y = np.array(["Ala ma kota", "Kota ma Alę", "A sierotka ma Rysia"])
print(y.size)
print(y.dtype)

[1 3 5 6]
4
int64
3
<U19


2D Array

In [ ]:
q = np.array([[1,2,3],[1,2,3],[0,0,0]])
print(q)
print(q[2][2])
print(q.ndim)
print(q.shape)

[[1 2 3]
 [1 2 3]
 [0 0 0]]
0
2
(3, 3)


In [5]:
np.random.seed(0)

Generowanie liczb pseudolosowych

In [6]:
np.random.randn(10,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [7]:
np.random.rand(10,4)

array([[0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051]])

In [10]:
np.random.randint(10)

6

In [15]:
np.random.randint(10, 40)

29

In [16]:
np.random.randint(10, 40, size=20)

array([26, 10, 32, 10, 16, 29, 24, 20, 29, 34, 38, 18, 23, 34, 39, 12, 13,
       12, 21, 23])

Wybór losowego elementu z listy

In [22]:
np.random.choice([20,10,40,2,3,4,5])

40

In [24]:
np.random.choice(["python", 'java', 'js', 'c++', 'c#'])

'python'

Tasowanie elementów w tablicy

In [26]:
data = np.arange(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
np.random.shuffle(data)
data

array([1, 7, 8, 4, 2, 0, 9, 6, 3, 5])